* Data Mining
  - Course: Data Mining - COMP 3431 2, Data Mining - COMP 4431 1
  - Class time: Tue, Thu  05:00 PM -  06:50 PM  |Engineering & Computer Science | Room 410
  - Instructor: /Pooran Singh Negi, pooran.negi@du.edu/ [[https://sites.google.com/site/poorannegi/][webpage]]
  - Office: 470
  - Office Hours: Tue, Thu,  6.50 p.m. - 8.50 p.m. Email for 1-on-1 help.
  - GTA: Mitchell Wright, GTA office hours to be added
  - Prerequisite: *Good understanding of Linear algebra, probability & statistics, calculus and some programming experience in python*
** Books 
   - [[http://www.dataminingbook.info/pmwiki.php][Data Mining and Analysis: Fundamental Concepts and Algorithms 1st Edition]]
   
Readings from the book will be posted on the course schedule


** Optional material online


* Course Description
It is recommended that you consult this github page often for material related to this course. You should check your e-mail periodically for messages.
Assignments will be upload here and in the [[https://canvas.du.edu/login/ldap][canvas]].

This course will provide introduction to some topics in data mining like classification, regression, clustering and knowledge discovery. We'll also go over
algebraic, statistical and geometric foundations of these topics. 

We'll use [[http://jupyter.org/][jupyter notebook/lab]] for in the class and homeworks assignments. You are expected to learn [[https://www.python.org/][python]] on your own via tutorials etc.
We'll also cover scientific python eco system libraries like numpy, sklearn and matplotlib. *Please see Software installation section to see how to setup computational environment.*


** Syllabus
*This syllabus is subject to change at the discretion of the instructor*.
- pattern mining,
- classification,
- regression
- clustering
- text mining


* Grading
*There will be  written/coding homework assignments, midterm , a final and a final project presentation. We'll drop one of your worst assignment grade*.
We'll allow 2 late homework with cutoff of 36 hours. We'll give *ceil(total_marks_obtained*exp(-(minutes late)/(24*60)))* marks  for  late submitted assignments via email.



** Dates

|---------------------------------------------------------------------------------------------------------+-----|
| Homework  and may be a final project challenge                                                          | 40% |
|---------------------------------------------------------------------------------------------------------+-----|
| Midterm, 7 th May in class                                                                              | 25% |
|---------------------------------------------------------------------------------------------------------+-----|
| Final, 11 th June in class                                                                              | 35% |
|---------------------------------------------------------------------------------------------------------+-----|



** Final course grading rubric

grade range [('A', >=93), ('A_minus', >=89), ('B_plus', >=85), ('B', >=81), ('B_minus', >=77), ('C_plus', >=73), ('C', >=69), ('C_minus', >=65),
 ('D_plus', >61), ('D', >=57), ('D_minus', >=53),  ('F', < 53)])

 
* Honor code
All members of the University of Denver community are expected to uphold the values of Integrity, Respect, and Responsibility.
These values embody the standards of conduct for students, faculty, staff, and administrators as members of the University community. 
Our institutional values are defined as:

Integrity: acting in an honest and ethical manner;

Respect: honoring differences in people, ideas, experiences, and opinions;

Responsibility: accepting ownership for one's own behavior and conduct.

Please respect DU [[https://www.du.edu/studentlife/studentconduct/honorcode.html][Honor Yourself, Honor the Code]]

* Students with Disabilities
Students with recognized disabilities will be provided reasonable
accommodations, appropriate to the course, upon documentation of the disability with a Student
Accommodation Form from the Disability Services Program. *To receive these accommodations, you must request the specific accommodations, by submitting them to the instructor in writing,
by the end of first week of classes.* Visit [[https://www.du.edu/studentlife/disability/][CAMPUS LIFE & INCLUSIVE EXCELLENCE]] webpage for details.

* Withdrawal Policy
Please see [[https://www.du.edu/registrar/calendar/][registrar calender]] for Academic deadlines. *We'll strictly follow the deadlines.*

 more to come
     
* Software Installation
** Python
We want everybody to have same experience using computational tools in data science tools 1. Please follow steps as
per your operating system.

*** Window based installation
Please install Windows Subsystem for Linux (WSL) on window 10. Follow the instruction in this post [[https://medium.com/hugo-ferreiras-blog/using-windows-subsystem-for-linux-for-data-science-9a8e68d7610c][Using Windows Subsystem for Linux for Data Science]]
by Hugo Ferreira for installing Linux. **ignore install Anaconda part.**

You can also watch this [[https://www.youtube.com/watch?v=Cvrqmq9A3tA][video]] to see installation of Windows 10 Bash & Linux Subsystem Setup.
** Linux /Mac users should already have bash command prompt
You can run *echo $0* to check current shell. Change to bash shell using  *chsh -s /bin/bash*

*One you are in Linux/Mac bash command prompt, Please follow following instructions*
** Python3 installation
Please follow instructions [[https://realpython.com/installing-python/][here]] to install python3 if it is not installed in your system. This link
also lists Windows Subsystem for Linux (WSL) for window 10(Windows 10 Creators or Anniversary Update).
I am using python 3.5.2. Hopefully any version of python 3 should work.

*** creating virtual environment and installing packages for data science tools 1
*Run following commands from  command prompt.*

- *apt-get install python3-venv*
- Using command line(*cd command*), go to the folder where you want to keep python file, notebooks related to this course.
- run *python3 -m venv /path/to/new/virtual/environment*
  + e.g. I ran *python3 -m venv dst1_env*
- To activate your environment run *source /path/to/new/virtual/environment/bin/activate*
  + e.g From this course directory I run, *source dst1_env/bin/activate*

- run *python3 -m pip install \-\-upgrade pip*. Note that there are 2 dashes in upgrade option.
- run *wget https://raw.githubusercontent.com/psnegi/data_science_tools1/master/requirements.txt*
- run *pip install -r requirements.txt*
- run *jupyter notebook* or *jupyter lab*. 
- In the browser you should see your current files.
- Click on the notebook you want to run.

- click on *RISE* slideshow extension in notebook, if you want to see notebook as slideshow.

To deactivate  python virtual environment, run *deactivate*

*** Python learning resources
You can also go to my  [[https://github.com/psnegi/PythonForReproducibleResearch][python for reproducible research]]  github repository and start by running pythonBasic.ipynb notebook.
I will go over basic of python and jupyter notebook.

   - [[https://try.jupyter.org/][try python notebook online without installing anything]]
   - [[http://pythontutor.com/live.html#mode%3Dedit][Runs and visualizes your python code]]
   - [[https://docs.python.org/3/tutorial/index.html][The Python Tutorial]]  

* Homeworks
*No late hw will be accepted*

|-------------------------------+-------+----------------------------------------+----------|
|                               | HW no | description and links                  | solution |
| Due date                      |       |                                        |          |
|-------------------------------+-------+----------------------------------------+----------|
|-------------------------------+-------+----------------------------------------+----------|
|                               |       |                                        |          |

* Course Activity

| Date      | Reading/Coding Assignments | class activity |
|-----------+----------------------------+----------------|
|-----------+----------------------------+----------------|
| 2 - April | read chapter 1 and 2       |                |
|           |                            |                |
|           |                            |                |
|           |                            |                |
|-----------+----------------------------+----------------|
|-----------+----------------------------+----------------|
|           |                            |                |
